/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ieee_cec15_cbcsono_DataGeneratorJNI */

#ifndef _Included_org_ieee_cec15_cbcsono_DataGeneratorJNI
#define _Included_org_ieee_cec15_cbcsono_DataGeneratorJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ieee_cec15_cbcsono_DataGeneratorJNI
 * Method:    rand
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_ieee_cec15_cbcsono_DataGeneratorJNI_rand__
  (JNIEnv *, jobject);

/*
 * Class:     org_ieee_cec15_cbcsono_DataGeneratorJNI
 * Method:    reseed
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_org_ieee_cec15_cbcsono_DataGeneratorJNI_reseed
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     org_ieee_cec15_cbcsono_DataGeneratorJNI
 * Method:    rand
 * Signature: (II)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_org_ieee_cec15_cbcsono_DataGeneratorJNI_rand__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_ieee_cec15_cbcsono_DataGeneratorJNI
 * Method:    shuffle
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_ieee_cec15_cbcsono_DataGeneratorJNI_shuffle
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ieee_cec15_cbcsono_DataGeneratorJNI
 * Method:    rotate
 * Signature: (I)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_org_ieee_cec15_cbcsono_DataGeneratorJNI_rotate
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
